// src/components/FloatingToolbar.tsx
import { createSignal, onCleanup, onMount } from "solid-js";

import { sidebarOpen, toggleSidebar } from "@/stores/sidebarSignal";
import { currentLocale, getT } from "@/i18n";

const t = getT(currentLocale);

const scrollToComments = () => {
  const target = document.querySelector("#comments");
  if (!target) {
    return;
  }

  target.scrollIntoView({ behavior: "smooth", block: "start" });
};

interface FloatingToolbarProps {
  hasNyxPlayer?: boolean;
}

function FloatingToolbar(props: FloatingToolbarProps) {
  const [scrollPercent, setScrollPercent] = createSignal(0);
  const [hasComments, setHasComments] = createSignal(false);
  const [hasNyxPlayer, setHasNyxPlayer] = createSignal(props.hasNyxPlayer ?? true);
  const [isMobile, setIsMobile] = createSignal(false);
  const [isVisible, setIsVisible] = createSignal(true);

  const percentLabel = () => `${Math.max(0, Math.round(scrollPercent()))}%`;

  const updateScrollPercent = () => {
    const scrollTop = window.scrollY || document.documentElement.scrollTop;
    const scrollHeight = document.documentElement.scrollHeight - window.innerHeight;
    setScrollPercent(scrollHeight > 0 ? (scrollTop / scrollHeight) * 100 : 0);
  };

  const updateDomPlugins = () => {
    setHasComments(Boolean(document.querySelector("#comments")));
    setHasNyxPlayer(
      Boolean(
        document.querySelector(
          "#nyx-player, .nyx-player, nyx-player, [data-nyx-player], .hyacine-slot-layout-bottom astro-island, [data-hyacine-slot='layout-bottom'] astro-island, astro-island[opts*='NyxPlayer']",
        ),
      ),
    );
  };

  const updateIsMobile = () => {
    setIsMobile(window.innerWidth <= 1023);
  };

  const toggleSidebarOnMobile = () => {
    if (!isMobile()) {
      return;
    }
    toggleSidebar();
  };

  onMount(() => {
    if (typeof window === "undefined" || typeof document === "undefined") {
      return;
    }

    updateScrollPercent();
    updateDomPlugins();
    updateIsMobile();

    let lastScrollY = window.scrollY;
    let idleTimer: ReturnType<typeof setTimeout> | null = null;

    const updateVisibility = () => {
      const currentScrollY = window.scrollY;
      const isScrollingUp = currentScrollY < lastScrollY;

      if (currentScrollY <= 8) {
        setIsVisible(true);
      } else if (isScrollingUp) {
        setIsVisible(true);
      } else {
        setIsVisible(false);
      }

      lastScrollY = currentScrollY;

      if (idleTimer) {
        clearTimeout(idleTimer);
      }

      idleTimer = setTimeout(() => {
        setIsVisible(true);
      }, 180);
    };

    window.addEventListener("scroll", updateScrollPercent, { passive: true });
    window.addEventListener("scroll", updateVisibility, { passive: true });
    window.addEventListener("resize", updateIsMobile, { passive: true });

    const observer = new MutationObserver(() => {
      updateDomPlugins();
    });
    observer.observe(document.body, { childList: true, subtree: true });

    onCleanup(() => {
      window.removeEventListener("scroll", updateScrollPercent);
      window.removeEventListener("scroll", updateVisibility);
      window.removeEventListener("resize", updateIsMobile);
      observer.disconnect();
      if (idleTimer) {
        clearTimeout(idleTimer);
      }
    });
  });

  return (
    <ul class={`floating-toolbar ${isVisible() ? "" : "is-hidden"}`}>
      <li class="tool top">
        <button
          type="button"
          onclick={() => window.scrollTo({ top: 0, behavior: "smooth" })}
          aria-label={t("toolbar.scrollTop")}
        >
          <i class="i-ri-arrow-up-line"></i>
        </button>
        <span class="percent">{percentLabel()}</span>
      </li>
      {hasComments() && (
        <li class="tool">
          <button type="button" onclick={scrollToComments} aria-label={t("toolbar.goToComments")}>
            <i class="i-ri-chat-1-line"></i>
          </button>
        </li>
      )}
      {hasNyxPlayer() && (
        <>
          <li class="tool">
            <button id="nyx-show-btn" type="button" aria-label={t("toolbar.togglePlayer")}>
              <i class="i-ri-music-2-line"></i>
            </button>
          </li>
          <li class="tool">
            <button id="nyx-play-btn" type="button" aria-label={t("toolbar.playPause")}>
              <i class="i-ri-play-circle-line"></i>
            </button>
          </li>
        </>
      )}
      <li class="tool mobile-only">
        <button
          type="button"
          onclick={toggleSidebarOnMobile}
          aria-label={t("toolbar.toggleSidebar")}
          aria-pressed={sidebarOpen()}
          class={sidebarOpen() ? "active" : ""}
        >
          <i class="i-ri-layout-right-2-line"></i>
        </button>
      </li>
    </ul>
  );
}

export default FloatingToolbar;

// src/components/FloatingToolbar.svelte
<script lang="ts">
  import { onMount } from "svelte";
  import { sidebarOpen, toggleSidebar } from "@/stores/sidebarStore";
  import { currentLocale, getT } from "@/i18n";
  import type { ShokaXThemeConfig } from "@/toolkit/themeConfig";

  const t = getT(currentLocale);

  interface Props {
    nyxPlayer?: ShokaXThemeConfig["nyxPlayer"];
  }

  let { nyxPlayer }: Props = $props();

  let scrollPercent = $state(0);
  let hasComments = $state(false);
  let isMobile = $state(false);
  let isVisible = $state(true);

  const percentLabel = $derived(`${Math.max(0, Math.round(scrollPercent))}%`);
  const nyxEnabled = $derived(
    Boolean(nyxPlayer?.enable && nyxPlayer.urls && nyxPlayer.urls.length > 0),
  );

  const updateScrollPercent = () => {
    const scrollTop = window.scrollY || document.documentElement.scrollTop;
    const scrollHeight =
      document.documentElement.scrollHeight - window.innerHeight;
    scrollPercent = scrollHeight > 0 ? (scrollTop / scrollHeight) * 100 : 0;
  };

  const updateHasComments = () => {
    hasComments = Boolean(document.querySelector("#comments"));
  };

  const updateIsMobile = () => {
    isMobile = window.innerWidth <= 1023;
  };

  const scrollToTop = () => {
    window.scrollTo({
      top: 0,
      behavior: "smooth",
    });
  };

  const scrollToComments = () => {
    const target = document.querySelector("#comments");
    if (!target) {
      return;
    }

    target.scrollIntoView({
      behavior: "smooth",
      block: "start",
    });
  };

  const toggleSidebarOnMobile = () => {
    if (!isMobile) {
      return;
    }

    toggleSidebar();
  };

  const initializeNyxPlayer = async () => {
    if (
      typeof window === "undefined" ||
      typeof document === "undefined" ||
      !nyxEnabled
    ) {
      return;
    }

    const player = document.querySelector("#player") as HTMLElement | null;
    const showBtn = document.querySelector("#nyx-show-btn");

    if (!player || !showBtn) {
      return;
    }

    if (player.dataset.nyxInited === "true") {
      return;
    }

    await import("nyx-player/style");
    const { initPlayer } = await import("nyx-player");

    initPlayer(
      "#player",
      "#nyx-show-btn",
      nyxPlayer?.urls || [],
      "#nyx-play-btn",
      nyxPlayer?.darkModeTarget || ':root[data-theme="dark"]',
      nyxPlayer?.preset || "shokax",
    );

    player.dataset.nyxInited = "true";
  };

  onMount(() => {
    if (typeof window === "undefined" || typeof document === "undefined")
      return;

    updateScrollPercent();
    updateHasComments();
    updateIsMobile();
    void initializeNyxPlayer();

    let lastScrollY = window.scrollY;
    let idleTimer: ReturnType<typeof setTimeout> | null = null;

    const updateVisibility = () => {
      const currentScrollY = window.scrollY;
      const isScrollingUp = currentScrollY < lastScrollY;

      if (currentScrollY <= 8) {
        isVisible = true;
      } else if (isScrollingUp) {
        isVisible = true;
      } else {
        isVisible = false;
      }

      lastScrollY = currentScrollY;

      if (idleTimer) {
        clearTimeout(idleTimer);
      }

      idleTimer = setTimeout(() => {
        isVisible = true;
      }, 180);
    };

    window.addEventListener("scroll", updateScrollPercent, { passive: true });
    window.addEventListener("scroll", updateVisibility, { passive: true });
    window.addEventListener("resize", updateIsMobile, { passive: true });

    let observer: MutationObserver | null = null;

    if (!hasComments) {
      observer = new MutationObserver(() => {
        if (hasComments) {
          observer?.disconnect();
          return;
        }

        updateHasComments();
        if (hasComments) {
          observer?.disconnect();
        }
      });

      observer.observe(document.body, {
        childList: true,
        subtree: true,
      });
    }

    return () => {
      window.removeEventListener("scroll", updateScrollPercent);
      window.removeEventListener("scroll", updateVisibility);
      window.removeEventListener("resize", updateIsMobile);
      observer?.disconnect();
      if (idleTimer) {
        clearTimeout(idleTimer);
      }
    };
  });
</script>

<ul class="floating-toolbar" class:is-hidden={!isVisible}>
  <li class="tool top">
    <button type="button" onclick={scrollToTop} aria-label={t("toolbar.scrollTop")}>
      <i class="i-ri-arrow-up-line"></i>
    </button>
    <span class="percent">{percentLabel}</span>
  </li>
  {#if hasComments}
    <li class="tool">
      <button type="button" onclick={scrollToComments} aria-label={t("toolbar.goToComments")}>
        <i class="i-ri-chat-1-line"></i>
      </button>
    </li>
  {/if}
  {#if nyxEnabled}
    <li class="tool">
      <button id="nyx-show-btn" type="button" aria-label={t("toolbar.togglePlayer")}>
        <i class="i-ri-music-2-line"></i>
      </button>
    </li>
    <li class="tool">
      <button id="nyx-play-btn" type="button" aria-label={t("toolbar.playPause")}>
        <i class="i-ri-play-circle-line"></i>
      </button>
    </li>
  {/if}
  <li class="tool mobile-only">
    <button
      type="button"
      onclick={toggleSidebarOnMobile}
      aria-label={t("toolbar.toggleSidebar")}
      aria-pressed={$sidebarOpen}
      class:active={$sidebarOpen}
    >
      <i class="i-ri-layout-right-2-line"></i>
    </button>
  </li>
</ul>

{#if nyxEnabled}
  <div id="player"></div>
{/if}

<style>
  .floating-toolbar {
    position: fixed;
    right: 1rem;
    bottom: 1rem;
    z-index: var(--z-floating);
    display: flex;
    flex-direction: column;
    gap: 0.4rem;
    padding: 0.5rem 0.4rem;
    margin: 0;
    list-style: none;
    border-radius: 0.75rem;
    background: var(--grey-1-a7);
    color: var(--text-color);
    border: 1px solid var(--grey-3);
    box-shadow: 0 0.5rem 1.25rem var(--box-bg-shadow);
    backdrop-filter: blur(12px);
    -webkit-backdrop-filter: blur(12px);
    transition:
      transform 0.2s ease,
      opacity 0.2s ease;
  }

  .floating-toolbar.is-hidden {
    transform: translateY(0.5rem);
    opacity: 0;
    pointer-events: none;
  }

  .tool {
    display: flex;
    align-items: center;
    justify-content: center;
    flex-direction: column;
    gap: 0.25rem;
  }

  .tool button {
    width: 2.125rem;
    height: 2.125rem;
    border-radius: 0.625rem;
    border: none;
    background: var(--grey-2-a0);
    color: inherit;
    cursor: pointer;
    display: flex;
    align-items: center;
    justify-content: center;
    transition: all 0.2s ease;
  }

  .tool button i {
    font-size: 1.1rem;
  }

  .tool button:hover,
  .tool button:focus-visible {
    color: var(--primary-color);
    background: var(--color-pink-light);
    box-shadow: 0 0.5rem 1rem var(--color-pink-light-a3);
  }

  .tool button.active {
    color: var(--primary-color);
    background: var(--color-pink-light);
  }

  .percent {
    font-size: 0.6875rem;
    line-height: 1;
    color: var(--grey-5);
  }

  .mobile-only {
    display: none;
  }

  @media (max-width: 1023px) {
    .mobile-only {
      display: flex;
    }
  }
</style>
